name: Coverage Badge Commit

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  coverage-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run tests with coverage
        run: |
          python -m pytest -q --cov=splurge_test_namer --cov-report=xml:coverage.xml --cov-report=html:htmlcov
      - name: Compute coverage percent
        id: coverage
        run: |
          if [ -f coverage.xml ]; then
            # extract line-rate
            pct=$(xmllint --xpath 'string(/coverage/@line-rate)' coverage.xml || true)
            if [ -n "$pct" ]; then
              pct100=$(awk -v v="$pct" 'BEGIN{printf("%.2f", v*100)}')
              echo "coverage_percent=$pct100" >> $GITHUB_OUTPUT
            else
              echo "coverage_percent=unknown" >> $GITHUB_OUTPUT
            fi
          else
            echo "coverage_percent=unknown" >> $GITHUB_OUTPUT
          fi
      - name: Update badge JSON
        run: |
          pct=${{ steps.coverage.outputs.coverage_percent }}
          color=lightgrey
          if [ "$pct" != "unknown" ]; then
            color=red
            if (( $(echo "$pct >= 90" | bc -l) )); then color=brightgreen; elif (( $(echo "$pct >= 75" | bc -l) )); then color=yellow; fi
            msg="$pct%"
          else
            msg="unknown"
          fi
          mkdir -p .github/badges
          jq -n --arg label "coverage" --arg message "$msg" --arg color "$color" '{schemaVersion:1, label:$label, message:$message, color:$color}' > .github/badges/coverage.json
      - name: Create PR with updated badge
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "ci: update coverage badge to ${{ steps.coverage.outputs.coverage_percent }}%"
          branch: "ci/coverage-badge-${{ github.run_id }}"
          title: "ci: update coverage badge"
          body: |
            This PR updates the coverage badge based on the latest test run (coverage: ${{ steps.coverage.outputs.coverage_percent }}%).
          labels: ci,coverage
