name: Coverage Badge Commit

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  coverage-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run tests with coverage
        run: |
          python -m pytest -q --cov=splurge_test_namer --cov-report=xml:coverage.xml --cov-report=html:htmlcov
      - name: Compute coverage percent
        id: coverage
        run: |
          if [ -f coverage.xml ]; then
            # extract line-rate
            pct=$(xmllint --xpath 'string(/coverage/@line-rate)' coverage.xml || true)
            if [ -n "$pct" ]; then
              pct100=$(awk -v v="$pct" 'BEGIN{printf("%.2f", v*100)}')
              echo "coverage_percent=$pct100" >> $GITHUB_OUTPUT
            else
              echo "coverage_percent=unknown" >> $GITHUB_OUTPUT
            fi
          else
            echo "coverage_percent=unknown" >> $GITHUB_OUTPUT
          fi
      - name: Update badge JSON
        run: |
          pct=${{ steps.coverage.outputs.coverage_percent }}
          color=lightgrey
          if [ "$pct" != "unknown" ]; then
            color=red
            if (( $(echo "$pct >= 90" | bc -l) )); then color=brightgreen; elif (( $(echo "$pct >= 75" | bc -l) )); then color=yellow; fi
            msg="$pct%"
          else
            msg="unknown"
          fi
          mkdir -p .github/badges
          jq -n --arg label "coverage" --arg message "$msg" --arg color "$color" '{schemaVersion:1, label:$label, message:$message, color:$color}' > .github/badges/coverage.json
      - name: Commit and push badge
        if: github.actor != 'github-actions[bot]'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/badges/coverage.json
          git commit -m "ci: update coverage badge to ${{ steps.coverage.outputs.coverage_percent }}%" || echo "no changes"
          git push origin HEAD:main || echo "push failed"
